apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: elasticdata
   namespace: kube-system
spec:
   accessModes:
      - ReadWriteOnce
   storageClassName: longhorn
   resources:
      requests:
         storage: 20Gi
